---
title: "LegalEASE Viz"
author: "Jordan Fan, John Gibbons, Elias Tavarez"
output: 
  bookdown::pdf_document2
date: "2024-04-14"
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

```{r include=FALSE}
library(xlsx)
library(ggplot2)
library(stringi)
library(dplyr)
library(magrittr)
library(patchwork)
library(tidyr)
library(knitr)
library(kableExtra)

inject_newlines <- function(v, substr_len, type = "newline") {
  v<-as.character(v)
  new_v <- vector()
  for(i in 1:length(v)){
    oldstr <- v[i]
    n_newlines <- nchar(oldstr) %/% substr_len
    if(n_newlines >= 1) {
      substr_index <- c(c(0, seq(1:n_newlines)*substr_len) + c(0:n_newlines), nchar(oldstr))
      newstr <- ""
      for(j in 1:(n_newlines+1)) {
        substr <- substr(oldstr, substr_index[j]+1, substr_index[j+1])
        if((substr_index[length(substr_index)] - substr_index[j]) > substr_len) {
          if(type == "newline"){
            substr <- stri_replace_last_regex(str=substr, pattern="\\s", replacement="\n")
          }
          else{
            substr <- stri_replace_last_regex(str=substr, pattern="\\s", replacement="\\\\")}
          
        }
        newstr <- paste0(newstr, substr)
      }
      new_v <- c(new_v, newstr)
    } else {
      new_v <- c(new_v, oldstr)
    }
  }
  return(new_v)
}
df= read.xlsx("congress-117-vis-stats.xlsx", sheetIndex = 1)
```

```{r include=FALSE}
df_1 = df
df_1$cur_text_len = ifelse(df_1$cur_text_len > 6000, 6001, df_1$cur_text_len)
df_1 = df_1 %>% mutate(bin = cut(cur_text_len, breaks = seq(0, 6500, 500)))

label_1_1 = seq(0, 6000, 500)
label_1_2 = seq(500, 6500, 500)
label_1 = c()
for(i in 1:length(label_1_1)){
  label_1 = c(label_1, paste0(label_1_1[i]+1, "-\n", label_1_2[i]))
}
label_1[i] = ">6000"

df_1$bin = factor(df_1$bin, levels = sort(unique(df_1$bin)), labels = label_1)

df_2 = df[df$cur_text_len > 6000,]
df_2$cur_text_len = ifelse(df_2$cur_text_len > 50000, 50001, df_2$cur_text_len)
df_2 = df_2 %>% mutate(bin = cut(cur_text_len, breaks = c(6000, 10000, 20000, 30000, 40000, 50000, 60000)))
label_2 = c("6001-\n10000", "10001-\n20000", "20001-\n30000", "30001-\n40000", "40001-\n50000", ">50000")
df_2$bin = factor(df_2$bin, levels = sort(unique(df_2$bin)), labels = label_2)


df_3 = df
df_3$cleaned_summary_len = ifelse(df_3$cleaned_summary_len > 300, 301, df_3$cleaned_summary_len)
df_3 = df_3 %>% mutate(bin = cut(cleaned_summary_len, breaks = seq(0, 350, 50)))

label_3_1 = seq(0, 300, 50)
label_3_2 = seq(50, 350, 50)
label_3 = c()
for(i in 1:length(label_3_1)){
  label_3 = c(label_3, paste0(label_3_1[i]+1, "-", label_3_2[i]))
}
label_3[i] = ">300"
df_3$bin = factor(df_3$bin, levels = sort(unique(df_3$bin)), labels = label_3)

df_4 = df
df_4$ratio = df_4$cleaned_summary_len / df_4$cur_text_len
df_4$ratio = ifelse(df_4$ratio > 0.65, 0.66, df_4$ratio)
df_4 = df_4 %>% mutate(bin = cut(ratio, breaks = seq(0, 0.7, 0.05)))

label_4_1 = seq(0, 0.65, 0.05)
label_4_2 = seq(0.05, 0.7, 0.05)
label_4 = c()
for(i in 1:length(label_4_1)){
  label_4 = c(label_4, paste0(label_4_1[i]+0.01, "-\n", label_4_2[i]))
}
label_4[i] = ">0.65"
df_4$bin = factor(df_4$bin, levels = sort(unique(df_4$bin)), labels = label_4)


df_cur_text_bins_1 = df_1 %>% group_by(bin) %>% summarize(n = n()) %>% mutate(percent = round(n/nrow(df) * 100, 1))
df_cur_text_bins_2 = df_2 %>% group_by(bin) %>% summarize(n = n()) %>% mutate(percent = round(n/nrow(df) * 100, 1))
df_summary_bins = df_3 %>% group_by(bin) %>% summarize(n = n()) %>% mutate(percent = round(n/nrow(df) * 100, 1))
df_ratio_bins = df_4 %>% group_by(bin) %>% summarize(n = n()) %>% mutate(percent = round(n/nrow(df) * 100, 1))


policy_areas_n = df %>% group_by(policy_areas) %>% summarize(n = n()) %>% mutate(percent = round(n/sum(n) * 100, 1))
policy_areas_n = policy_areas_n[order(policy_areas_n$n, decreasing = T),]
policy_areas_n$policy_areas = factor(policy_areas_n$policy_areas, levels = rev(policy_areas_n$policy_areas))

policy_areas_group = df %>% group_by(group, policy_areas) %>% summarize(n = n())
policy_areas_group$group = factor(policy_areas_group$group, levels = c("train", "val", "test"))
policy_areas_group = policy_areas_group[order(policy_areas_group$group, policy_areas_group$n, decreasing = c(F, T)),]
policy_areas_group$policy_areas = factor(policy_areas_group$policy_areas, levels = unique(policy_areas_group$policy_areas))

policy_areas_group_spread = policy_areas_group %>% tidyr::spread(policy_areas, n)

policy_areas_text_len = df[,c("policy_areas", "cur_text_len")]
policy_areas_text_len$cur_text_len = ifelse(policy_areas_text_len$cur_text_len >= 6000, 6000, policy_areas_text_len$cur_text_len)
policy_areas_text_len$policy_areas = factor(policy_areas_text_len$policy_areas, levels = unique(policy_areas_group$policy_areas))
group1 = levels(policy_areas_text_len$policy_areas)[1:16] 
group2 = levels(policy_areas_text_len$policy_areas)[17:length(unique(policy_areas_text_len$policy_areas))]

policy_areas_text_len1 = policy_areas_text_len[policy_areas_text_len$policy_areas %in% group1,]
policy_areas_text_len1$policy_areas = inject_newlines(policy_areas_text_len1$policy_areas, 20)
policy_areas_text_len2 = policy_areas_text_len[policy_areas_text_len$policy_areas %in% group2,]
policy_areas_text_len2$policy_areas = inject_newlines(policy_areas_text_len2$policy_areas, 20)

summary_fre = data.frame("Group" = rep("Reference", 3), "Model" = c("BART", "Reference", "T5"), "FRE" = c(NA, round(mean(df$cleaned_summary_fre), 2), NA))
model_fre = data.frame("Group" = rep(c("Baseline", "TF-Extractive", "BERTSum\nExtractive", "Abstractive"), each = 3), "Model" = rep(c("BART", "PEGASUS", "T5"), 4), "FRE" = c(26.97, 24.81, 26.62, 23.62, 26.26, 27.76, 27.86, 33.13, 30.03,27.16, 27.25, 28.72))
df_fre = rbind(summary_fre, model_fre)
df_fre$FRE = round(df_fre$FRE, 1)
df_fre$Group = factor(df_fre$Group, levels = unique(df_fre$Group))
df_fre$Model = factor(df_fre$Model, levels = c("BART", "PEGASUS", "T5", "Reference"))


gg_cur_text_len_1 <- ggplot(df_cur_text_bins_1, aes(x = bin, y = percent)) +
  geom_bar(color = "black", fill = "skyblue", stat = "identity") + geom_text(aes(x = bin, y = percent, label = paste0(percent, "%")), vjust = -0.5) + 
  labs(title = "Document Word Count Distribution") + xlab("# Words") + ylab("Percent") + theme(panel.background = element_blank(), axis.title.y = element_text(angle = 0, vjust = 0.5))

gg_cur_text_len_2 <- ggplot(df_cur_text_bins_2, aes(x = bin, y = percent)) +
  geom_bar(color = "black", fill = "skyblue", stat = "identity") + geom_text(aes(x = bin, y = percent, label = paste0(percent, "%")), vjust = -0.5) + 
  labs(title = "Document Word Count (>6000 words) Distribution") + xlab("# Words") + ylab("Percent") + theme(panel.background = element_blank(), axis.title.y = element_text(angle = 0, vjust = 0.5))

gg_summary <- ggplot(df_summary_bins, aes(x = bin, y = percent)) +
  geom_bar(color = "black", fill = "darkred", stat = "identity") + geom_text(aes(x = bin, y = percent, label = paste0(percent, "%")), vjust = -0.5) + 
  labs(title = "Summary Word Count Distribution") + xlab("# Words") + ylab("Percent") + theme(panel.background = element_blank(), axis.title.y = element_text(angle = 0, vjust = 0.5))

gg_ratio <- ggplot(df_ratio_bins, aes(x = bin, y = percent)) +
  geom_bar(color = "black", fill = "gold", stat = "identity") + geom_text(aes(x = bin, y = percent, label = paste0(percent, "%")), vjust = -0.5) + 
  labs(title = "Summary to Full Text Word Count Ratio Distribution") + xlab("Ratio") + ylab("Percent") + theme(panel.background = element_blank(), axis.title.y = element_text(angle = 0, vjust = 0.5))


gg_policy_overall = ggplot(policy_areas_n, aes(x = policy_areas, y = percent)) +
  geom_bar(color = "black", fill = "skyblue", stat = "identity") + coord_flip() + geom_text(aes(x = policy_areas, y = percent, label = paste0(percent, "%", "(", n, ")")), hjust = -0.1) + 
  labs(title = "Policy Area Distribution") + xlab("") + ylab("Percent") + theme(panel.background = element_blank(), axis.title.y = element_text(angle = 0, vjust = 0.5)) + ylim(0, 17)


gg_policy_area_wc1 = ggplot() + geom_boxplot(aes(x = policy_areas_text_len1$policy_areas, y = policy_areas_text_len1$cur_text_len), color = "black", fill = "skyblue") + theme(panel.background = element_blank(), axis.title.y = element_text(angle = 0, vjust = 0.5), axis.text.x = element_text(angle = 90, vjust = 0.5, hjust = 0.8, margin = margin(0,0,0,0))) + ylab("Word\nCount") + xlab("Policy Area") + labs(title = "Word Count Distribution by Policy Area (1)") + scale_y_continuous(breaks = c(0, 1000, 2000, 3000, 4000, 5000, 6000), labels = c("0", "1000", "2000", "3000", "4000", "5000", "6000+"))

gg_policy_area_wc2 = ggplot() + geom_boxplot(aes(x = policy_areas_text_len2$policy_areas, y = policy_areas_text_len2$cur_text_len), color = "black", fill = "skyblue") + theme(panel.background = element_blank(), axis.title.y = element_text(angle = 0, vjust = 0.5), axis.text.x = element_text(angle = 90, vjust = 0.5, hjust = 0.8, margin = margin(0,0,0,0))) + ylab("Word\nCount") + xlab("Policy Area") + labs(title = "Word Count Distribution by Policy Area (2)") + scale_y_continuous(breaks = c(0, 1000, 2000, 3000, 4000, 5000, 6000), labels = c("0", "1000", "2000", "3000", "4000", "5000", "6000+"))

gg_fre = ggplot(df_fre, aes(x = Group, fill = Model, y = FRE)) + 
  geom_bar(color = "black", stat = "identity", position = "dodge") + 
  geom_text(aes(x = Group, y = FRE, label = FRE), position = position_dodge(width = 1), vjust = -0.5, size = 3) + 
  ylim(0, 40) + 
  labs(title = "Mean Flesch Reading Ease Across Experiments and Models") + xlab("Experiment") + ylab("Score") + theme(panel.background = element_blank(), axis.title.y = element_text(angle = 0, vjust = 0.5))
gg_fre = gg_fre + scale_fill_manual(values = c("darkblue", "tan", "darkgreen", "darkred"))

#gg_cur_text_len_1
#gg_cur_text_len_2
#gg_summary
#gg_ratio

```

```{r, echo=F}
gg_cur_text_len_1
```

\newpage


```{r, echo=F, fig.cap='Summary Word Count and Ratio Distribution', fig.pos='!b', fig.height=5, fig.width=10}
(gg_cur_text_len_2 | gg_summary)

```

```{r}
gg_ratio
```



```{r echo=F, fig.height=7, fig.width=12}
gg_policy_overall
```
```{r echo=F}
gg_policy_area_wc1
```

```{r echo=F}
gg_policy_area_wc2
```


```{r}
gg_fre
```


